"""permissions

Revision ID: 3f89e5cd53c3
Revises: 4f183e83c98f
Create Date: 2024-09-04 14:02:38.469957

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "3f89e5cd53c3"
down_revision: Union[str, None] = "4f183e83c98f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
