"""permissions

Revision ID: 4f183e83c98f
Revises: f4a78c41ade8
Create Date: 2024-09-04 14:01:17.334440

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "4f183e83c98f"
down_revision: Union[str, None] = "f4a78c41ade8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
