"""permissions

Revision ID: 8ce4f7af3a98
Revises: c39aa09fc283
Create Date: 2024-09-04 13:43:21.154891

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "8ce4f7af3a98"
down_revision: Union[str, None] = "c39aa09fc283"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
